### ISSUE TITLE
Possible memory-leak feedback loop?

### ISSUE THREAD

**Issue by chris-pikul** [warner/magic-wormhole-mailbox-server#12]
Not that it probably matters that much, since taking down the relay is fairly pointless for anyone to actually do. But reading through the code, I noticed something in the cleaning process that I think keeps all applications, ever, in memory.

https://github.com/warner/magic-wormhole-mailbox-server/blob/60c924a28c35370a9904bd63b28da49591aa92fb/src/wormhole_mailbox_server/server.py#L589-L596

Because get all apps is used, every app_id from the db is loaded, and then through `app = self.get_app(app_id)` it is put into the dictionary, spawning the object.

Since the apps dictionary itself is never pruned, any nefarious script kiddie could just ping made up apps all day long filling the dictionary right?

I suppose the fix would be during pruning to get the remaining in-use applications after mailbox/nameplate pruning, then clean out the dictionary from there.

**Comment by warner** [comment]
Hmm.. I'd have to think about it. If there are any active channels for an appid (any open nameplates, mailboxes, or messages), then yeah `get_all_apps()` will make sure there's an `AppNamespace` instance for it. If nobody has used that appid for a while, the DB rows for its nameplates/mailboxes/messages should get pruned, and after that point, `get_all_apps()` should stop returning it.

The `AppNamespace` object will still exist in `self._apps` for as long as the process runs, but it ought to be empty (specifically its `self._mailboxes` dict should be empty once they're all pruned). So it consumes a little space, but not a lot, and only until the next time the server crashes :). Looking at my logs, apparently I reboot the public mailbox server about once every two weeks, on average, mostly for OS upgrades of some sort.

But yeah, I think you're right, someone could consume a chunk of memory by looping through all possible appids and just opening a mailbox on each one. They'll get removed after 20-ish minutes, but the memory will be used up for as long as they care to continue the attack.

`prune_all_apps()` should probably be named something like `prune_contents_of_all_apps()` instead.. maybe we should have another function that looks for `AppNamespace` instances that are empty, and delete them.

**Comment by chris-pikul** [comment]
Yeah seems like a minor issue if it really is one. I was mostly pointing out that the first step of that function is too get all the app IDs from the database *before* pruning. And since `self.get_app(app_id)` will create the in-memory dictionary for the IDs, an object is spawned. Only at the end of the function does the DB actually get pruned, but never the in-memory cache. So if I'm reading the logic correctly, the Server's `self._apps` dictionary only grows and never shrinks.

Tiny memory footprint of course. And a restart will obviously clear that right up :)
