### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by Baeumla** [warner/magic-wormhole-mailbox-server#2]
The install instructions are missing. Even though it is pretty straight-forward, I think both, the installation from source code as well as the `pip install magic-wormhole-mailbox-server`  should breifly be mentioned either in the documentation or in the README. 

I can make a PR with the updated documentation if @warner tells me where he wants to have it.

Edit: Minor typo in the README in the link for the transit relay.

**Comment by warner** [comment]
Thanks.. let's put it in the README, if it'll only be a paragraph or two.

**Comment by warner** [comment]
closed in #5, thanks!
